/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.flowexp.ui.AbstractFlowexpUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FlowexpUiModule extends AbstractFlowexpUiModule {
  public FlowexpUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
