/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.flowexp.ui.internal.FlowexpActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FlowexpExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(FlowexpActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		FlowexpActivator activator = FlowexpActivator.getInstance();
		return activator != null ? activator.getInjector(FlowexpActivator.ORG_XTEXT_EXAMPLE_FLOWEXP_FLOWEXP) : null;
	}

}
