/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.flowexp.parser.antlr.internal.InternalFlowexpParser;
import org.xtext.example.flowexp.services.FlowexpGrammarAccess;

public class FlowexpParser extends AbstractAntlrParser {

	@Inject
	private FlowexpGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFlowexpParser createParser(XtextTokenStream stream) {
		return new InternalFlowexpParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public FlowexpGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FlowexpGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
