/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.flowexp.flowexp.Model

@ExtendWith(InjectionExtension)
@InjectWith(FlowexpInjectorProvider)
class FlowexpParsingTest {
	@Inject
	ParseHelper<Model> parseHelper

	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

	}

	@Test
	def void loadModel2() {
		val result = parseHelper.parse('''
			people
			person "truc";
			person "Machin2";
			person "Test3333";
			
			greetings
			Hello truc!
			Hello Machin2!
			Hello Test3333!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

	}

}
