/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.flowexp.ui.internal.FlowexpActivator;

public class FlowexpUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FlowexpActivator.getInstance().getInjector("org.xtext.example.flowexp.Flowexp");
	}

}
