/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.validation;

import com.google.common.base.Objects;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.validation.Check;
import org.xtext.example.flowexp.flowexp.FlowexpPackage;
import org.xtext.example.flowexp.flowexp.Person;
import org.xtext.example.flowexp.validation.AbstractFlowexpValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FlowexpValidator extends AbstractFlowexpValidator {
  @Check
  public void checkNameUppercase(final Person person) {
    final String premierChar = person.getName().substring(0, 1).toUpperCase();
    final String premierCharBis = person.getName().substring(0, 1);
    boolean _notEquals = (!Objects.equal(premierChar, premierCharBis));
    if (_notEquals) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Name must start with an upper case");
      this.error(_builder.toString(), person, 
        FlowexpPackage.eINSTANCE.getPerson_Name());
    }
  }
}
