/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.flowexp.services.FlowexpGrammarAccess;

@SuppressWarnings("all")
public class FlowexpSyntacticSequencer extends AbstractSyntacticSequencer {

	protected FlowexpGrammarAccess grammarAccess;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (FlowexpGrammarAccess) access;
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getInitBatchRule())
			return getInitBatchToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getPeriodicityRule())
			return getPeriodicityToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * InitBatch:
	 * 	"template"
	 * ;
	 */
	protected String getInitBatchToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "template";
	}
	
	/**
	 * Periodicity:
	 * 	"daily"|"monthly"|"semester"
	 * ;
	 */
	protected String getPeriodicityToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "daily";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

}
