/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp;

import org.xtext.example.flowexp.FlowexpStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FlowexpStandaloneSetup extends FlowexpStandaloneSetupGenerated {
  public static void doSetup() {
    new FlowexpStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
