/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.ide;

import org.xtext.example.flowexp.ide.AbstractFlowexpIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FlowexpIdeModule extends AbstractFlowexpIdeModule {
}
