/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.flowexp.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.flowexp.flowexp.ExpNb;
import org.xtext.example.flowexp.flowexp.FlowexpPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp Nb</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpNbImpl extends MinimalEObjectImpl.Container implements ExpNb
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpNbImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlowexpPackage.Literals.EXP_NB;
  }

} //ExpNbImpl
