/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.flowexp.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.flowexp.flowexp.ExpNbOne;
import org.xtext.example.flowexp.flowexp.FlowexpPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp Nb One</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpNbOneImpl extends ExpNbImpl implements ExpNbOne
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpNbOneImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlowexpPackage.Literals.EXP_NB_ONE;
  }

} //ExpNbOneImpl
