/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.flowexp.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.flowexp.flowexp.ExpNbBatch;
import org.xtext.example.flowexp.flowexp.FlowexpPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp Nb Batch</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpNbBatchImpl extends ExpNbImpl implements ExpNbBatch
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpNbBatchImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlowexpPackage.Literals.EXP_NB_BATCH;
  }

} //ExpNbBatchImpl
