/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.flowexp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Nb</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.flowexp.flowexp.FlowexpPackage#getExpNb()
 * @model
 * @generated
 */
public interface ExpNb extends EObject
{
} // ExpNb
