/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.flowexp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Nb One</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.flowexp.flowexp.FlowexpPackage#getExpNbOne()
 * @model
 * @generated
 */
public interface ExpNbOne extends ExpNb
{
} // ExpNbOne
