/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.flowexp;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.flowexp.flowexp.FlowexpPackage
 * @generated
 */
public interface FlowexpFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FlowexpFactory eINSTANCE = org.xtext.example.flowexp.flowexp.impl.FlowexpFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Exp Nb</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exp Nb</em>'.
   * @generated
   */
  ExpNb createExpNb();

  /**
   * Returns a new object of class '<em>Init</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Init</em>'.
   * @generated
   */
  Init createInit();

  /**
   * Returns a new object of class '<em>Init One</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Init One</em>'.
   * @generated
   */
  InitOne createInitOne();

  /**
   * Returns a new object of class '<em>Exp Nb Batch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exp Nb Batch</em>'.
   * @generated
   */
  ExpNbBatch createExpNbBatch();

  /**
   * Returns a new object of class '<em>Exp Nb One</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exp Nb One</em>'.
   * @generated
   */
  ExpNbOne createExpNbOne();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  FlowexpPackage getFlowexpPackage();

} //FlowexpFactory
