/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.flowexp;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Init One</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.flowexp.flowexp.InitOne#getFilename <em>Filename</em>}</li>
 *   <li>{@link org.xtext.example.flowexp.flowexp.InitOne#getTval <em>Tval</em>}</li>
 *   <li>{@link org.xtext.example.flowexp.flowexp.InitOne#getPval <em>Pval</em>}</li>
 *   <li>{@link org.xtext.example.flowexp.flowexp.InitOne#getSrval <em>Srval</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.flowexp.flowexp.FlowexpPackage#getInitOne()
 * @model
 * @generated
 */
public interface InitOne extends Init
{
  /**
   * Returns the value of the '<em><b>Filename</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Filename</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filename</em>' attribute list.
   * @see org.xtext.example.flowexp.flowexp.FlowexpPackage#getInitOne_Filename()
   * @model unique="false"
   * @generated
   */
  EList<String> getFilename();

  /**
   * Returns the value of the '<em><b>Tval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tval</em>' attribute.
   * @see #setTval(int)
   * @see org.xtext.example.flowexp.flowexp.FlowexpPackage#getInitOne_Tval()
   * @model
   * @generated
   */
  int getTval();

  /**
   * Sets the value of the '{@link org.xtext.example.flowexp.flowexp.InitOne#getTval <em>Tval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tval</em>' attribute.
   * @see #getTval()
   * @generated
   */
  void setTval(int value);

  /**
   * Returns the value of the '<em><b>Pval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pval</em>' attribute.
   * @see #setPval(int)
   * @see org.xtext.example.flowexp.flowexp.FlowexpPackage#getInitOne_Pval()
   * @model
   * @generated
   */
  int getPval();

  /**
   * Sets the value of the '{@link org.xtext.example.flowexp.flowexp.InitOne#getPval <em>Pval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pval</em>' attribute.
   * @see #getPval()
   * @generated
   */
  void setPval(int value);

  /**
   * Returns the value of the '<em><b>Srval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Srval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Srval</em>' attribute.
   * @see #setSrval(int)
   * @see org.xtext.example.flowexp.flowexp.FlowexpPackage#getInitOne_Srval()
   * @model
   * @generated
   */
  int getSrval();

  /**
   * Sets the value of the '{@link org.xtext.example.flowexp.flowexp.InitOne#getSrval <em>Srval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Srval</em>' attribute.
   * @see #getSrval()
   * @generated
   */
  void setSrval(int value);

} // InitOne
