/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.flowexp.flowexp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Init</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.flowexp.flowexp.FlowexpPackage#getInit()
 * @model
 * @generated
 */
public interface Init extends EObject
{
} // Init
